name: Basic validation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - name: Set up JDK 21
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn clean compile
